<!doctype html>
<html>

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
</head>

<body>
    <div class="flex items-center justify-center min-h-screen bg-gray-100 bg-green-600">
        <div class="px-8 py-6 mx-4 mt-4 text-left bg-white shadow-lg md:w-1/3 lg:w-1/3 sm:w-1/3">
            <h3 class="text-2xl font-bold text-center text-green-500">Delete</h3>
            <form action="" method="post">
                <div class="mt-4">
                    <div>
                        <input type="text" name="id" placeholder="ObjectID" class="text-center w-full px-4 py-2 mt-2 border rounded-md focus:outline-none focus:ring-1 focus:ring-green-600">
                    </div>
                    <span class="text-xs text-red-400"></span>
                    <div class="flex">
                        <button class="w-full px-6 py-2 mt-4 text-white bg-green-500 rounded-lg hover:bg-green-900">Delete Inforamtion</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</body>

</html>